"""empty message

Revision ID: 055cecebd844
Revises: fe53a5a222be
Create Date: 2022-02-07 22:07:37.388402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055cecebd844'
down_revision = 'fe53a5a222be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_artists',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'genre_id')
    )
    op.create_table('genre_venues',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'genre_id')
    )
    op.drop_constraint('genres_artist_id_fkey', 'genres', type_='foreignkey')
    op.drop_constraint('genres_venue_id_fkey', 'genres', type_='foreignkey')
    op.drop_column('genres', 'venue_id')
    op.drop_column('genres', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('genres', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('genres_venue_id_fkey', 'genres', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('genres_artist_id_fkey', 'genres', 'artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.drop_table('genre_venues')
    op.drop_table('genre_artists')
    # ### end Alembic commands ###
