"""empty message

Revision ID: c0756167e704
Revises: 
Create Date: 2021-08-10 11:47:57.791922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0756167e704'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('genres', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'genres', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'genres', 'artist', ['artist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', type_='foreignkey')
    op.drop_constraint(None, 'genres', type_='foreignkey')
    op.drop_column('genres', 'artist_id')
    op.drop_column('genres', 'venue_id')
    # ### end Alembic commands ###
